### ISSUE TITLE
ocamlfind: Package `opium' not found Cannot run Ocamlfind.

### ISSUE THREAD

**Issue by decapo01** [rgrinberg/opium#84]
after installation when i try to run

```ocamlbuild -pkg opium hello_world.native```

I've been trying for about an hour and I cannot find a solution.

**Comment by decapo01** [comment]
so i think i found part of the problem in that opam is not installing opium.  I thought it did because i didnt recieve an error message affter the first attempt after switching to the 4.03 compiler.  When i retry installing opium i get an error Unbound module Lwt_log

**Comment by XVilka** [comment]
@decapo01 should be fixed in https://github.com/rgrinberg/opium/commit/473e3e1b14b87a4a4f56437a732fea1bb8194a75

**Comment by jcoleman-techempower** [comment]
Still unable to do this myself

**Comment by jcoleman-techempower** [comment]
<img width="626" alt="screen shot 2019-01-02 at 2 42 58 pm" src="https://user-images.githubusercontent.com/43076128/50616757-b53ff500-0e9e-11e9-82db-2ac24948d131.png">

**Comment by jcoleman-techempower** [comment]
Now, obviously ocamlbuild is not in my path. I can verify that by adding `RUN which ocamlbuild` in my Dockerfile. The point of my contribution to this issue is that the setting of opam, opium, and ocamlbuild should all be part of some sort of automation so that end-users and developers don't have to jump through hoops just to get a simple Opium app going

**Comment by jcoleman-techempower** [comment]
Using the bleeding edge release still doesn't fix this for me

**Comment by rgrinberg** [comment]
What error do you get?

**Comment by jcoleman-techempower** [comment]
@rgrinberg Simply just

```
opium: /bin/sh: 1: ocamlbuild: not found
```

**Comment by anuragsoni** [comment]
@jcoleman-techempower You could try using the opam2 docker images hosted at: https://hub.docker.com/r/ocaml/opam2/tags

**Comment by anuragsoni** [comment]
Closing as there hasn't been a response for quite some time now. Please re-open if still interested.
